### PR TITLE
Allow to configure the user key in JWT token

### PR DESCRIPTION
**Pull request by sroze**
If the user identifier key is not `id` in the JWT token, it is important to be able to configure which one should be used.

**Backward compatibility break**: the default value being `sub` has per the JWT specification, it will probably break setups using the `id` key only.

### CODE REVIEW

**Comment by italolelis** [comment]
Hi @sroze. Can u please gofmt this file `pkg/jwt/middleware.go`? CI is failing because of that.

**Comment by sroze** [comment]
@italolelis done :)

**Comment by italolelis** [comment]
@sroze Please check CI, there are some lint rules that are breaking.

**Comment by italolelis** [comment]
Closing this PR for inactivity. Please feel free to reopen it if necessary.

**Pull request closed without merging**
