### PR TITLE
Fixed minor misspell and gofmt simplify notices

### PR DESCRIPTION
**Pull request by vgarvardt**

### CODE REVIEW

**Comment by rafaeljesus** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/hellofresh/api-gateway/pull-request/152/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/api-gateway) [Approved with PullApprove](https://pullapprove.com/hellofresh/api-gateway/pull-request/152/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/api-gateway)

**Review by rafaeljesus — APPROVED** [review]
Let's add golint in a next step 👍

**Comment by vgarvardt** [comment]
@rafaeljesus we already have it, https://github.com/hellofresh/janus/blob/master/build/test.sh#L52, and it did not help, but we also have https://goreportcard.com/report/github.com/hellofresh/janus

**Review by italolelis — COMMENTED** [review]
:+1:

**Comment by kieranajp** [comment]
:shipit:

[Approved with PullApprove](https://pullapprove.com/hellofresh/api-gateway/pull-request/152/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/api-gateway) [Approved with PullApprove](https://pullapprove.com/hellofresh/api-gateway/pull-request/152/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/api-gateway) [Approved with PullApprove](https://pullapprove.com/hellofresh/api-gateway/pull-request/152/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/api-gateway)

**Pull request merged**
