### PR TITLE
Simplify Version command

### LINKED ISSUE #446: Simplify cmd Version command
Currently, The version of the cmd tool is set using an additional function which can be seen [here](https://github.com/hellofresh/janus/blob/master/cmd/version.go#L10).

The Cobra Library already has a feature to set the version using the underlying struct field `Version`.

>  // Version defines the version for this command. If this value is non-empty and the command does not
     // define a "version" flag, a "version" boolean flag will be added to the command and, if specified,
     // will print content of the "Version" variable. A shorthand "v" flag will also be added if the
    // command does not define one.
````
    Version string
````
Official docs: https://github.com/spf13/cobra/blob/5cdf8e26ba7046dd743463f60102ab52602c6428/command.go#L90

My proposal to improve it : 

```go
// NewRootCmd creates a new instance of the root command
func NewRootCmd(version string) *cobra.Command {
	ctx := context.Background()

	cmd := &cobra.Command{
		Use:     "janus",
		Version: version,    <======== Sets the version 
         .......
        ..................
}
```
I have already tested it and working as expected. Please check the output below:

```sh
$ ./janustest --version
janus version 0.0.0-dev
```

### PR DESCRIPTION
**Pull request by itsksaurabh**
closes #446

### CODE REVIEW

**Comment by vgarvardt** [comment]
@itsksaurabh Thank you for the contribution!

**Review by vgarvardt — APPROVED** [review]

**Comment by vgarvardt** [comment]
👍 

Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by itsksaurabh** [comment]
@vgarvardt Thanks for your approval. Glad to be a part of this awesome project!

**Comment by fftorres** [comment]
+1

Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by harshal-shah** [comment]
+1

Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr

**Pull request merged**
