### PR TITLE
Url parameters for whole target

### PR DESCRIPTION
**Pull request by Serjick**
## What does this PR do?
A few sentences describing the overall goals of the pull request's commits.

Allow to use url parameteres not only in path but for whole target. E.g.
```
...
      "listen_path":"/{service}/*",
      "upstreams":{
         "balancing":"weight",
         "targets":[
            {
               "target":"http://{service}:8080",
               "weight":100
            }
         ]
      },
...
```

### CODE REVIEW

**Comment by vgarvardt** [comment]
Hello @Serjick. Thank you for your contribution. Implementation looks good but could you please add some tests for it? Would be great to have BDD (godog/features) tests here.

**Comment by Serjick** [comment]
Hello @vgarvardt! Such simple test is enough?

**Comment by vgarvardt** [comment]
👍 

Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by RTodorov** [comment]
+1

Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr

**Review by vgarvardt — APPROVED** [review]

**Pull request merged**
