### PR TITLE
Bumped base golang version to 1.8

### PR DESCRIPTION
**Pull request by vgarvardt**

### CODE REVIEW

**Comment by kieranajp** [comment]
:shipit:

[Approved with PullApprove](https://pullapprove.com/hellofresh/api-gateway/pull-request/81/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/api-gateway)

**Comment by vgarvardt** [comment]
Final image size did not change - `340 MB`

**Comment by kieranajp** [comment]
That seems high, probably we're missing an `&& rm -rf /var/cache/apk/*` somewhere @vgarvardt

**Comment by vgarvardt** [comment]
Most likely we're not removing installed deps - will check this

**Pull request merged**
