### PR TITLE
Add pod annotations to Janus chart

### PR DESCRIPTION
**Pull request by aleksandrzhiliaev**
## What does this PR do?
This PR adds pod annotation to Janus chart

### CODE REVIEW

**Review by s4nji — APPROVED** [review]

**Comment by s4nji** [comment]
+1

Approved with Zappr  Approved with Zappr

**Review by vgarvardt — APPROVED** [review]

**Comment by vgarvardt** [comment]
👍 

Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by s4nji** [comment]
+1

Approved with Zappr  Approved with Zappr

**Comment by vgarvardt** [comment]
👍 

Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by fftorres** [comment]
+1

Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr

**Pull request merged**
